### ISSUE TITLE
Terminal clear command is unable to clear itself.

### ISSUE THREAD

**Issue by subodhk01** [codefest-iit-bhu/codefest-app#131]
<img width="495" alt="Screenshot 2020-04-11 at 00 35 45" src="https://user-images.githubusercontent.com/19875783/79016362-65190d80-7b8c-11ea-8268-1491138f9513.png">

**Comment by nishantwrp** [comment]
@shivanshs9 I think that is expected?

**Comment by subodhk01** [comment]
@nishantwrp why?

**Comment by subodhk01** [comment]
#132

**Comment by shivanshs9** [comment]
Closed via #132
